### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by dougcodes** [begmaroman/go-micro-boilerplate#10]
Thank you for creating this boilerplate. I have a few questions.

1) Do you plan on creating a utility to create a new "micro-service", for instance now you have "account-svc" and "rest-api-svc". What if I want to create a payment micro service? For now I get it that I can copy and paste the folders, but adding a utility like, go-micro-create "payments" and that generates all the files would be awesome.

2) Where exactly is NATS magic happening? I only see the definition of the NATS server in docker-compose. But I do not see where you publish and subscribe a message. So for example, if an HTTP request comes, hits the "rest-api-svc", where do you publish a message exactly? I only see a call to the grpc "micro".

3) Do you plan to add protected endpoints example? ( With bearer token for instance )

4) How about adding examples to one relation db ( postgres ), one for non-relational example ( mongodb ) and one for in memory cache ( redis ) ?

5) Swagger: What endpoint do I hit to see the endpoints locally? localhost/swagger ?

Thanks

**Comment by begmaroman** [comment]
@dougcodes 
> Do you plan on creating a utility to create a new "micro-service", for instance now you have "account-svc" and "rest-api-svc". What if I want to create a payment micro service? For now I get it that I can copy and paste the folders, but adding a utility like, go-micro-create "payments" and that generates all the files would be awesome.

What would be nice, will think about that. 

> Where exactly is NATS magic happening? I only see the definition of the NATS server in docker-compose. But I do not see where you publish and subscribe a message. So for example, if an HTTP request comes, hits the "rest-api-svc", where do you publish a message exactly? I only see a call to the grpc "micro".

All of the magic is done by micro framework. You can read README.md, there is small description about NATS.

> Do you plan to add protected endpoints example? ( With bearer token for instance )

Yea, I may add an example of how to use that. 

> How about adding examples to one relation db ( postgres ), one for non-relational example ( mongodb ) and one for in memory cache ( redis ) ?

Good idea, I need more resources to do so :) 

> Swagger: What endpoint do I hit to see the endpoints locally? localhost/swagger ?

I'll add a service to docker-compose so you can open Swagger UI.

**Comment by begmaroman** [comment]
@dougcodes 

> Swagger: What endpoint do I hit to see the endpoints locally? localhost/swagger ?

Just pull the latest changes, and run `docker-compose up -d cvspot-api-spec `, after that Swagger UI will be reachable on `localhost:4005`
