### ISSUE TITLE
Error while running docker-compose up --build

### ISSUE THREAD

**Issue by MortezaAghili** [begmaroman/go-micro-boilerplate#2]
I wanna try your boilerplate but there is an issue with `account-svc` while upping the container (or build it)

here you can see the result:
![Screenshot from 2020-07-20 16-39-55](https://user-images.githubusercontent.com/6826680/87936435-11319500-caa8-11ea-8562-b438a0e31e05.png)

**Comment by ihuke** [comment]
The same error.
![image](https://user-images.githubusercontent.com/10142086/90615531-d5bcee80-e23e-11ea-9348-a36426418b34.png)

**Comment by gahfaustino** [comment]
@ihuke thanks. This work for me.

**Comment by begmaroman** [comment]
Fixed in the last commit
