### ISSUE TITLE
Request Timeout error

### ISSUE THREAD

**Issue by apoldev** [begmaroman/go-micro-boilerplate#7]
Hello!
I tried running your code via docker-compose

But requests to /user - works every other time.

Sometimes I get array of User objects.  ( []. or [{...},{...},{...}] if i have users )
But I also regularly get this error

`{"id": "go.micro.client", "code": 408, "detail": "call timeout: context deadline exceeded", "status": "Request Timeout"}`

OS: MacOS Catalina
Docker: Engine version 19.03.12

What could be the problem?
Source code didn't change.
Thanks

**Comment by begmaroman** [comment]
@apoldev fixed in the last commit, check again please

**Comment by ppusapati** [comment]
@apoldev https://github.com/begmaroman/go-micro-boilerplate/issues/12#issue-807985573
