### ISSUE TITLE
Docker Compose build error

### ISSUE THREAD

**Issue by ppusapati** [begmaroman/go-micro-boilerplate#8]
build github.com/begmaroman/go-micro-boilerplate/services/account-svc/cmd/account-svc: cannot load github.com/begmaroman/go-micro-boilerplate/proto/account-svc: no matching versions for query "latest"
ERROR: Service 'account-svc' failed to build : The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go install ./services/account-svc/cmd/account-svc' returned a non-zero code: 1

![Screenshot 2020-12-23 at 1 51 13 PM](https://user-images.githubusercontent.com/5749576/102975590-54e06d00-4526-11eb-8f51-2a375c396315.png)

**Comment by begmaroman** [comment]
Fixed in the last commit
