### ISSUE TITLE
Docker compose fails

### ISSUE THREAD

**Issue by dougcodes** [begmaroman/go-micro-boilerplate#9]
After executing: 

docker-compose up -d --build

I'm getting:

Step 2/8 : RUN CGO_ENABLED=0 GOOS=linux go install ./services/account-svc/cmd/account-svc
 ---> Running in 8439d5fc3427
# github.com/coreos/etcd/clientv3/balancer/picker
/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/err.go:37:44: undefined: balancer.PickOptions
/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/picker/roundrobin_balanced.go:55:54: undefined: balancer.PickOptions
# github.com/coreos/etcd/clientv3/balancer/resolver/endpoint
/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:114:78: undefined: resolver.BuildOption
/go/pkg/mod/github.com/coreos/etcd@v3.3.18+incompatible/clientv3/balancer/resolver/endpoint/endpoint.go:182:31: undefined: resolver.ResolveNowOption
ERROR: Service 'account-svc' failed to build : The command '/bin/sh -c CGO_ENABLED=0 GOOS=linux go install ./services/account-svc/cmd/account-svc' returned a non-zero code: 2

**Comment by begmaroman** [comment]
@dougcodes pull the latest changes and try again please.

**Comment by dougcodes** [comment]
@begmaroman  - Thanks that worked..

**Comment by ppusapati** [comment]
@dougcodes Have you been able to successfully run this?

**Comment by ppusapati** [comment]
@dougcodes https://github.com/begmaroman/go-micro-boilerplate/issues/12#issue-807985573
